[phases.setup]
nixPkgs = ["python311", "gcc", "g++"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd ai_tender_system && gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 web.app:create_app()"
