#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AI提示词模块

提供各类检查所需的提示词
"""

from .completeness_checker import COMPLETENESS_CHECK_PROMPT, COMPLETENESS_CHECK_SYSTEM
from .seal_checker import SEAL_CHECK_PROMPT, SEAL_CHECK_SYSTEM
from .page_checker import PAGE_CHECK_PROMPT, PAGE_CHECK_SYSTEM, INDEX_CHECK_PROMPT, INDEX_CHECK_SYSTEM
from .date_checker import DATE_CHECK_PROMPT, DATE_CHECK_SYSTEM
from .price_checker import PRICE_CHECK_PROMPT, PRICE_CHECK_SYSTEM
from .performance_checker import PERFORMANCE_CHECK_PROMPT, PERFORMANCE_CHECK_SYSTEM

__all__ = [
    'COMPLETENESS_CHECK_PROMPT', 'COMPLETENESS_CHECK_SYSTEM',
    'SEAL_CHECK_PROMPT', 'SEAL_CHECK_SYSTEM',
    'PAGE_CHECK_PROMPT', 'PAGE_CHECK_SYSTEM',
    'INDEX_CHECK_PROMPT', 'INDEX_CHECK_SYSTEM',
    'DATE_CHECK_PROMPT', 'DATE_CHECK_SYSTEM',
    'PRICE_CHECK_PROMPT', 'PRICE_CHECK_SYSTEM',
    'PERFORMANCE_CHECK_PROMPT', 'PERFORMANCE_CHECK_SYSTEM',
]
